# coding: utf-8
#
#		SConstruct
#		Sat Nov  7 20:24:42 2009
#
#	This file is the part of the Master Thesis.
#	Academia: RTU, DITF (Latvia, Riga)
#
#	Authorship, 2009
#		Antons Jeļkins
#		  antons.jelkins@rtu.lv
#		  kane@mail.berlios.de
#

import os
Import("ku2")
env = ku2.Fork()

#	Disable debugging on release:
if env.build_mode == "release":
	env.Append(CPPDEFINES = ["NDEBUG"])

#	We are only reading INI files:
env.Append(CPPDEFINES = ["INI_READONLY"])

#	minIni library
minIni = env.StaticLibrary("minIni", "minIni.c")
ku2.RegisterComponent("minIni", minIni)

ku2.RegisterLibrary("minIni",
                    libs = [str(minIni[0])],
                    libpath = [os.getcwd()],
                    includes = [os.getcwd() + "/.."])
