#
#	SConstruct file for Kane Utilities 2 (Qt components)
#		J. Anton, Copyright 2010
#

scenarios = []

build = ARGUMENTS.get("build", "graphviz,paragraph")
notbuild = ARGUMENTS.get("notbuild", "")
if "graphviz" in build and not "graphviz" in notbuild:
	scenarios += ["graphviz/SConstruct"]
if "paragraph" in build and not "paragraph" in notbuild:
	scenarios += ["paragraph/SConstruct"]

Import("ku2")
SConscript(scenarios, "ku2")
