#
#	SConstruct file for Kane Utilities 2 (qt:paragraph)
#		J. Anton, Copyright 2010+
#

Import("QtProgram ku2qt")
env = ku2qt.QtFork()
env.EnableQt4Modules(["QtGui"])
env.ApplyLibrary("graphviz")
env.Append(CPPPATH = ["src"])

env.AddSources(Split("""
	src/main.cc
	src/misc/Settings.cc
	src/ui/MainWindow.cc
	src/ui/WorkingArea.cc
	"""))

env.AddResources(Split("""
	img/img
	translations/translations
	"""))

env.AddTranslations(Split("""
	translations/paragraph_en
	translations/paragraph_ru
	translations/paragraph_lv
	"""))

ku2paragraph = QtProgram(env, "ku2paragraph")
Default(env.translations, ku2paragraph)
