#
#	SConstruct file for Kane Utilities 2
#		J. Anton, Copyright 2007
#

scenarios = []

build = ARGUMENTS.get("build", "modules,tools")
notbuild = ARGUMENTS.get("notbuild", "")
if not "core" in notbuild:
	scenarios += ["core/SConstruct"]
if "modules" in build and not "modules" in notbuild:
	scenarios += ["modules/SConstruct"]
if "tools" in build and not "tools" in notbuild:
	scenarios += ["tools/SConstruct"]

SConscript(scenarios)
