#
#	SConstruct file for Kane Utilities 2 (qt:graphviz)
#		J. Anton, Copyright 2010+
#

import os
Import("ku2 ku2qt")

env = ku2qt.QtFork()
env.EnableQt4Modules(["QtGui"])
env.ParseConfig("pkg-config libgvc --cflags --libs")
env.ApplyLibrary("ku2core")

env.AddSources(Split("""
	context.cc
	graph.cc
	node.cc
	edge.cc
	"""))

ku2graphviz = env.Ku2SharedLibrary("ku2graphviz")
Default(ku2graphviz)

ku2.RegisterLibrary("libgvc-includes", config = ["pkg-config libgvc --cflags"])
ku2.RegisterLibrary("graphviz",
                    libs = [str(ku2graphviz[0])],
                    libpath = [os.getcwd()],
                    includes = [os.getcwd() + "/.."],
                    deps = ["ku2core-includes", "libgvc-includes"])
