#
#	SConstruct file for Kane Utilities 2 (qt:graphviz)
#		J. Anton, Copyright 2006+
#

env = Environment(tools = ["default", "qt4"], CPPPATH = ["../../core"])
env.EnableQt4Modules([
	"QtCore",
	"QtGui"])
env.ParseConfig("pkg-config libgvc --cflags --libs")

sources = Split("""
	context.cc
	graph.cc
	node.cc
	edge.cc
	""")

ku2graphviz = env.SharedLibrary("ku2graphviz", sources)
Default(ku2graphviz)
