#!/bin/bash
#	Update the Kane Utilities 2 (core) stats.

echo Updating stats for Kane Utilities 2...
for ifile in `grep ^\#FILES: $0 | sed s/^\#FILES://`; do
	cp -f ${ifile}.pre $ifile &&
	grep ^\#RULE: $0 | sed s/^\#RULE:// | 
	(
		while read S_IN S_OUT; do
			sed s/$S_IN/$S_OUT/ $ifile > ${ifile}.tmp &&
			mv ${ifile}.tmp $ifile
		done
	)
done

chmod a+x makerpm.ku2

#	Files and rules for stat changing.
#FILES: ku2/ku2info.h ku2.pc ku2.spec makerpm.ku2

#RULE: __st_VER_MAJ 1
#RULE: __st_VER_MIN 6
#RULE: __st_RELEASE 10
#RULE: __st_PREFIX \\/usr
